### ISSUE TITLE
Blade Service Builder runtime error

### ISSUE THREAD

**Issue by jrao** [rotty3000/blade#211] opened 2016-01-19 22:58 UTC
The gradle/blade.servicebuilder modules seem to be compiling fine. However, when I deploy the modules to Liferay, I get the attached runtime exception. The portlet in the web module cannot be added to a page; it does not even appear in the Add menu.

[blade-servicebuilder-error.txt](https://github.com/rotty3000/blade/files/96684/blade-servicebuilder-error.txt)

**Comment by AndyWu2015** [comment] 2016-01-20 00:57
OK I will take a look at it .

**Comment by jrao** [comment] 2016-01-21 17:12
@AndyWu2015 FYI, I think this issue is a result of nothing more than a mismatch between my Liferay version and the 7.0.0-SNAPSHOT version. When I replaced all occurences of '7.0.0-SNAPSHOT' with '7.0.0-b3' in blade/gradle/build.gradle and in the build.gradle files in the blade.servicebuilder modules, everything works. Can deploy and use portlet from blade.servicebuilder.web module.

**Comment by AndyWu2015** [comment] 2016-01-22 01:30
Thanks for reporting @jrao , I am searching for this and got some result : it maybe the package name error: 
com.liferay.portal.NoSuchModelException 
should be 
com.liferay.portal.exception.NoSuchModelException
I will continue to search and report it here .

**Comment by deadcyclo** [comment] 2016-01-22 19:03
Same issue on master built a few minutes ago.

**Comment by deadcyclo** [comment] 2016-01-22 20:11
I think this is an issue with the portal-service in nexus. The latest version in nexus was built on the 15th of January, while the NoSuchModelException was moved at about the same time. But, the build in nexus is obviously older than the change (From manually inspecting the jar file).

**Comment by rotty3000** [comment] 2016-01-22 20:22
perhaps you could build the portal source, and that will automatically push portal artifacts into the .m2. then I think you could proceed. Of course this would be temporary until we get the released artifacts sorted out.

**Comment by deadcyclo** [comment] 2016-01-22 22:30
or push them to my own nexus server that I use for my own stuff ;)

But yeah. I build the portal from master every time I play with the blade project anyway, so I guess I just need to find out how to force gradle to use stuff from the .m2 cache (I've never really used gradle much before)

**Comment by rotty3000** [comment] 2016-01-23 14:36
hmm, gradle will automatically use the local `.m2` repository before going remote. I wonder if perhaps that is your issue. you may be using core artifacts that are too new for the modules you are referring to. A simple test is to temporarily rename your `.m2` dir to something like `.m2.bak` and try your project builds over again (but not the portal one).

**Comment by david-truong** [comment] 2016-01-23 20:21
You need to add mavenLocal() to your repositories for it to use your local

**Comment by deadcyclo** [comment] 2016-01-23 21:37
@rotty3000 Nope. First thing I after I got the error was to clear both my maven and my gradle caches before trying again.

@david-truong Thanks :)

If I have time tomorrow, I'll try your suggestion @rotty3000 and see if that temporarily fixes it.

**Comment by rotty3000** [comment] 2016-01-24 14:38
@david-truong too true.. I forgot about that!

**Comment by AndyWu2015** [comment] 2016-01-25 02:15
Yeah @david-truong  @deadcyclo  , in build.gradle we force gradle to use remote jars instead of local maven repo , because we assume that the nexus server in liferay is always working well.
So if you get something wrong , you could try to build stuff locally and add mavenLocal() into your build.gradle.

**Comment by rotty3000** [comment] 2016-03-04 05:38
tonight I confirmed the service builder examples work when using the latest dependency:

`com.liferay.portal:com.liferay.portal.kernel;version='[1.0.1,2.0.0)'`

to replace the old portal-service dependency.

I'll leave this open until I can commit the changes for all 4 subprojects tomorrow.

**Comment by gamerson** [comment] 2016-03-10 00:08
Changes have been committed here: https://github.com/rotty3000/blade/pull/242

@jrao please reopen if the problem persists.

**Closed by gamerson** 2016-03-10 00:08 UTC
