### ISSUE TITLE
trouble with the jsp-portlet as well

### ISSUE THREAD

**Issue by deadcyclo** [rotty3000/blade#250] opened 2016-03-10 12:04 UTC
Seems the jsp portlet is having issues as well. (On current master). It shows up in the list of portlets without a title, and it isn't including Language.properties.

**Comment by csierra** [comment] 2016-03-10 12:10
hey, 

this is a duplicate of #247

**Comment by csierra** [comment] 2016-03-10 12:11
we have a fix on its way

**Comment by deadcyclo** [comment] 2016-03-10 12:13
sigh. that's what I get for not paying attention ;)

**Comment by csierra** [comment] 2016-03-10 13:05
haha :joy:

**Closed** 2016-03-11 13:46 UTC
