### ISSUE TITLE
Missing blade samples build by bndtools

### ISSUE THREAD

**Issue by lawrence-lee** [rotty3000/blade#223] opened 2016-03-01 23:10 UTC
Complete list: 
```
blade.authenticator.shiro-1.0.0-SNAPSHOT.jar
blade.authfailure-1.0.0-SNAPSHOT.jar
blade.configurationaction-1.0-SNAPSHOT.jar
blade.friendlyurl-1.0-SNAPSHOT.jar
blade.gogo-1.0.0-SNAPSHOT.jar
blade.hook.jsp-1.0.0-SNAPSHOT.jar
blade.indexerpostprocessor-1.0.0-SNAPSHOT.jar
blade.jsf.portlet.ds-1.0.0-SNAPSHOT.jar
blade.lifecycle.loginpreaction-1.0.0-SNAPSHOT.jar
blade.modellistener-1.0-SNAPSHOT.jar
blade.pollprocessor-1.0-SNAPSHOT.jar
blade.portlet.actioncommand-1.0.0-SNAPSHOT.jar
blade.portlet.blueprint-1.0.0-SNAPSHOT.jar
blade.portlet.ds-1.0.0-SNAPSHOT.jar
blade.portlet.filter-1.0.0-SNAPSHOT.jar
blade.portlet.jsp-1.0.0-SNAPSHOT.jar
blade.portlet.osgiapi-1.0.0-SNAPSHOT.jar
blade.rest-1.0-SNAPSHOT.jar
blade.service.hook.user-1.0.0-SNAPSHOT.jar
blade.servicebuilder.api-1.0.0-SNAPSHOT.jar
blade.servicebuilder.svc-1.0.0-SNAPSHOT.jar
blade.servicebuilder.test-1.0.0-SNAPSHOT.jar
blade.servicebuilder.web-1.0.0-SNAPSHOT.jar
blade.strutsaction-1.0-SNAPSHOT.jar
blade.strutsportletaction-1.0-SNAPSHOT.jar
```
bndtools list:
```
blade.authenticator.shiro-1.0.0.jar
blade.authfailure-1.0.0.jar
blade.hook.jsp-1.0.0.jar
blade.portlet.actioncommand-1.0.0.jar
blade.portlet.blueprint-1.0.0.jar
blade.portlet.ds-1.0.0.jar
blade.portlet.filter-1.0.0.jar
blade.portlet.osgiapi-1.0.0.jar
blade.run-0.0.0.jar
blade.service.hook.user-1.0.0.jar
blade.servicebuilder.api-1.0.0.jar
blade.servicebuilder.svc-1.0.0.jar
blade.servicebuilder.test-0.0.0.jar
blade.servicebuilder.web-1.0.0.jar
blade.trackmen-1.0.0.jar
```

**Comment by gamerson** [comment] 2016-03-01 23:17
So we should probably switch the blade samples away from SNAPSHOT versions
since we aren't publishing these in a rolling way.

On Tue, Mar 1, 2016 at 5:10 PM, Lawrence Lee <notifications@github.com>
wrote:

> Complete list:
>
> blade.authenticator.shiro-1.0.0-SNAPSHOT.jar
> blade.authfailure-1.0.0-SNAPSHOT.jar
> blade.configurationaction-1.0-SNAPSHOT.jar
> blade.friendlyurl-1.0-SNAPSHOT.jar
> blade.gogo-1.0.0-SNAPSHOT.jar
> blade.hook.jsp-1.0.0-SNAPSHOT.jar
> blade.indexerpostprocessor-1.0.0-SNAPSHOT.jar
> blade.jsf.portlet.ds-1.0.0-SNAPSHOT.jar
> blade.lifecycle.loginpreaction-1.0.0-SNAPSHOT.jar
> blade.modellistener-1.0-SNAPSHOT.jar
> blade.pollprocessor-1.0-SNAPSHOT.jar
> blade.portlet.actioncommand-1.0.0-SNAPSHOT.jar
> blade.portlet.blueprint-1.0.0-SNAPSHOT.jar
> blade.portlet.ds-1.0.0-SNAPSHOT.jar
> blade.portlet.filter-1.0.0-SNAPSHOT.jar
> blade.portlet.jsp-1.0.0-SNAPSHOT.jar
> blade.portlet.osgiapi-1.0.0-SNAPSHOT.jar
> blade.rest-1.0-SNAPSHOT.jar
> blade.service.hook.user-1.0.0-SNAPSHOT.jar
> blade.servicebuilder.api-1.0.0-SNAPSHOT.jar
> blade.servicebuilder.svc-1.0.0-SNAPSHOT.jar
> blade.servicebuilder.test-1.0.0-SNAPSHOT.jar
> blade.servicebuilder.web-1.0.0-SNAPSHOT.jar
> blade.strutsaction-1.0-SNAPSHOT.jar
> blade.strutsportletaction-1.0-SNAPSHOT.jar
>
> bndtools list:
>
> blade.authenticator.shiro-1.0.0.jar
> blade.authfailure-1.0.0.jar
> blade.hook.jsp-1.0.0.jar
> blade.portlet.actioncommand-1.0.0.jar
> blade.portlet.blueprint-1.0.0.jar
> blade.portlet.ds-1.0.0.jar
> blade.portlet.filter-1.0.0.jar
> blade.portlet.osgiapi-1.0.0.jar
> blade.run-0.0.0.jar
> blade.service.hook.user-1.0.0.jar
> blade.servicebuilder.api-1.0.0.jar
> blade.servicebuilder.svc-1.0.0.jar
> blade.servicebuilder.test-0.0.0.jar
> blade.servicebuilder.web-1.0.0.jar
> blade.trackmen-1.0.0.jar
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rotty3000/blade/issues/223>.
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by gamerson** [comment] 2016-03-01 23:20
That way you wouldn't have to hack around the filename differences.

On Tue, Mar 1, 2016 at 5:17 PM, Greg Amerson <gregory.amerson@liferay.com>
wrote:

> So we should probably switch the blade samples away from SNAPSHOT versions
> since we aren't publishing these in a rolling way.
>
> On Tue, Mar 1, 2016 at 5:10 PM, Lawrence Lee <notifications@github.com>
> wrote:
>
>> Complete list:
>>
>> blade.authenticator.shiro-1.0.0-SNAPSHOT.jar
>> blade.authfailure-1.0.0-SNAPSHOT.jar
>> blade.configurationaction-1.0-SNAPSHOT.jar
>> blade.friendlyurl-1.0-SNAPSHOT.jar
>> blade.gogo-1.0.0-SNAPSHOT.jar
>> blade.hook.jsp-1.0.0-SNAPSHOT.jar
>> blade.indexerpostprocessor-1.0.0-SNAPSHOT.jar
>> blade.jsf.portlet.ds-1.0.0-SNAPSHOT.jar
>> blade.lifecycle.loginpreaction-1.0.0-SNAPSHOT.jar
>> blade.modellistener-1.0-SNAPSHOT.jar
>> blade.pollprocessor-1.0-SNAPSHOT.jar
>> blade.portlet.actioncommand-1.0.0-SNAPSHOT.jar
>> blade.portlet.blueprint-1.0.0-SNAPSHOT.jar
>> blade.portlet.ds-1.0.0-SNAPSHOT.jar
>> blade.portlet.filter-1.0.0-SNAPSHOT.jar
>> blade.portlet.jsp-1.0.0-SNAPSHOT.jar
>> blade.portlet.osgiapi-1.0.0-SNAPSHOT.jar
>> blade.rest-1.0-SNAPSHOT.jar
>> blade.service.hook.user-1.0.0-SNAPSHOT.jar
>> blade.servicebuilder.api-1.0.0-SNAPSHOT.jar
>> blade.servicebuilder.svc-1.0.0-SNAPSHOT.jar
>> blade.servicebuilder.test-1.0.0-SNAPSHOT.jar
>> blade.servicebuilder.web-1.0.0-SNAPSHOT.jar
>> blade.strutsaction-1.0-SNAPSHOT.jar
>> blade.strutsportletaction-1.0-SNAPSHOT.jar
>>
>> bndtools list:
>>
>> blade.authenticator.shiro-1.0.0.jar
>> blade.authfailure-1.0.0.jar
>> blade.hook.jsp-1.0.0.jar
>> blade.portlet.actioncommand-1.0.0.jar
>> blade.portlet.blueprint-1.0.0.jar
>> blade.portlet.ds-1.0.0.jar
>> blade.portlet.filter-1.0.0.jar
>> blade.portlet.osgiapi-1.0.0.jar
>> blade.run-0.0.0.jar
>> blade.service.hook.user-1.0.0.jar
>> blade.servicebuilder.api-1.0.0.jar
>> blade.servicebuilder.svc-1.0.0.jar
>> blade.servicebuilder.test-0.0.0.jar
>> blade.servicebuilder.web-1.0.0.jar
>> blade.trackmen-1.0.0.jar
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/rotty3000/blade/issues/223>.
>>
>
>
>
> --
> Greg Amerson
> Liferay Developer Tools
> Liferay, Inc. www.liferay.com
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by rotty3000** [comment] 2016-03-01 23:21
+1

**Comment by rotty3000** [comment] 2016-03-03 03:47
However, the issue is that @lawrence-lee couldn't find all the packaged jars. However they ARE there even though they don't end up all in the `./dist/` dir for some reason.

However, you find them if you run this command:
```
]$ find -name *.jar -not -path "./cnf/*" -not -path "./dist/*" -not -path "./.gradle*" | sort
./blade.authenticator.shiro/generated/blade.authenticator.shiro.jar
./blade.authfailure/generated/blade.authfailure.jar
./blade.configurationaction/generated/blade.configurationaction.jar
./blade.friendlyurl/generated/blade.friendlyurl.jar
./blade.gogo/generated/blade.gogo.jar
./blade.hook.jsp/generated/blade.hook.jsp.jar
./blade.indexerpostprocessor/generated/blade.indexerpostprocessor.jar
./blade.jsf.portlet.ds/generated/blade.jsf.portlet.ds.jar
./blade.lifecycle.loginpreaction/generated/blade.lifecycle.loginpreaction.jar
./blade.modellistener/generated/blade.modellistener.jar
./blade.pollprocessor/generated/blade.pollprocessor.jar
./blade.portlet.actioncommand/generated/blade.portlet.actioncommand.jar
./blade.portlet.blueprint/generated/blade.portlet.blueprint.jar
./blade.portlet.ds/generated/blade.portlet.ds.jar
./blade.portlet.filter/generated/blade.portlet.filter.jar
./blade.portlet.jsp/generated/blade.portlet.jsp.jar
./blade.portlet.osgiapi/generated/blade.portlet.osgiapi.jar
./blade.rest/generated/blade.rest.jar
./blade.run/generated/blade.run.jar
./blade.servicebuilder.api/generated/blade.servicebuilder.api.jar
./blade.servicebuilder.svc/generated/blade.servicebuilder.svc.jar
./blade.servicebuilder.test/generated/blade.servicebuilder.test.jar
./blade.servicebuilder.web/generated/blade.servicebuilder.web.jar
./blade.service.hook.user/generated/blade.service.hook.user.jar
./blade.strutsaction/generated/blade.strutsaction.jar
./blade.strutsportletaction/generated/blade.strutsportletaction.jar
./blade.trackmen/generated/blade.trackmen.jar
]$
```
So I'm going to close this issue. We can open a new issue to figure out why they don't all end up in dist.

**Closed by rotty3000** 2016-03-03 03:47 UTC
